# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Excalidraw systemd service
  ansible.builtin.stat:
    path: "{{ sysd_docker_service_path }}/{{ excalidraw_identifier }}.service"
  register: excalidraw_service_stat

- name: Uninstall Excalidraw systemd services and files
  when: excalidraw_service_stat.stat.exists | bool
  block:
    - name: Ensure Excalidraw systemd service is stopped
      ansible.builtin.service:
        name: "{{ excalidraw_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Excalidraw systemd service does not exist
      ansible.builtin.file:
        path: "{{ sysd_docker_service_path }}/{{ excalidraw_identifier }}.service"
        state: absent

    - name: Ensure Excalidraw container network does not exist via community.docker.docker_network
      when: sysd_docker_net_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ excalidraw_container_network }}"
        state: absent
      register: excalidraw_network_deletion_result

    - name: Ensure Excalidraw container network does not exist via ansible.builtin.command
      when: sysd_docker_net_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ sysd_docker_host_command }} network rm
          {{ excalidraw_container_network }}
      register: excalidraw_network_deletion_result
      changed_when: excalidraw_container_network in excalidraw_network_deletion_result.stdout

    - name: Ensure Excalidraw path does not exist
      ansible.builtin.file:
        path: "{{ excalidraw_base_path }}"
        state: absent
